apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-canary-demo
  labels:
    app: fastapi-canary-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi-canary-demo
  template:
    metadata:
      labels:
        app: fastapi-canary-demo
    spec:
      containers:
      - name: fastapi-container
        image: ganesh243/fastapi-canary-demo:latest
        ports:
        - containerPort: 80
